---
apiVersion: apps/v1
kind: replicaset
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  minReadyseconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: apache
          image: nginx:latest
          ports:
            - containerPort: 80